chore(ci): push_dockerhubがtrueかつDocker Hubのユーザ名が設定されていない場合、エラーにする

diff --git a/.github/workflows/build-engine-container.yml b/.github/workflows/build-engine-container.yml
--- a/.github/workflows/build-engine-container.yml
+++ b/.github/workflows/build-engine-container.yml
@@ -48,6 +48,12 @@ jobs:
           echo "ghcr_repository=ghcr.io/${{ github.repository_owner }}/voicevox_engine" >> "$GITHUB_OUTPUT"
 
           : # Docker HubのDockerイメージリポジトリ
+          # push_dockerhubがtrueかつDocker Hubのユーザ名が設定されていない場合、エラー
+          if [[ "${{ github.event.inputs.push_dockerhub }}" == "true" && -z "${{ vars.DOCKERHUB_USERNAME }}" ]]; then
+              echo "::error::GitHub Actionsの構成変数にDOCKERHUB_USERNAMEが設定されていません"
+              exit 1
+          fi
+
           echo "dockerhub_repository=${{ vars.DOCKERHUB_USERNAME }}/voicevox_engine" >> "$GITHUB_OUTPUT"
 
   build-docker:
